### ISSUE TITLE
Not able to handle cancelled scenario.

### ISSUE THREAD

**Issue by im-v** [feilfeilundfeil/flutter_in_app_update#69] opened 2021-04-11 14:49 UTC
Note: All testing happens in the release build and internal test track.
For testing, I decrease my current build number compare to the one that is available in the play store and then creating a release build by this command - __flutter build apk --flavor release__. 
Steps to reproduce: 
1) Call __checkForUpdate()__  if "__androidAppUpdate.getUpdateDesciption.updateAvailable__" true will called (__startFlexibleUpdate()__)
2) Show update dialog to the user. then the user clicks on Update. 
3) Once the update downloaded then again show a pop-up to use for installing the downloaded update. If the user installs everything works perfectly. 
4) But If the user clicks on a canceled button on the dialog created By me and closes the application. Then the user opens the application again then we again called __checkForUpdate()__ but this time in the callback of this method. The variable called "__androidAppUpdate.getUpdateDesciption.updateAvailable__" are come as false.
5) As this variable coming false I am not able to start to install.
6) I also try to call __completeFlexibleUpdate__ directly when  next time the application open but it's giving platform exception that please first call __checkForUpdate()__ 

I didn't find any documentation for the canceled scenario. Any help will be appreciated.

--Flutter doctor -v-- 

![Screenshot 2021-04-11 at 8 15 54 PM](https://user-images.githubusercontent.com/74063024/114308816-babb2980-9b02-11eb-96ec-b014a6afa6c4.png)

**Comment by im-v** [comment] 2021-04-11 14:59
@jonasbark @mig35 @MooNag @creativecreatorormaybenot Please check and let me know if need more details.

**Comment by jonasbark** [comment] 2022-02-16 18:39
Dupe of https://github.com/feilfeilundfeil/flutter_in_app_update/issues/30

**Closed by jonasbark** 2022-02-16 18:39 UTC
